### ISSUE TITLE
Mobile: Top Blue Bar is missing

### ISSUE THREAD

**Issue by cpoey** [walkward/veridicon-issues#14]
Top Blue Bar, which is present in DT, is not in mobile environment.  I understand that the bar and all of the content cannot be easily displayed in mobile, but the following need to be somewhere toward the top, in mobile:

• My List (when logged in)
• My Account
• Log Out
• Cart (present only when logged in) Should at least be present once a non-logged in user has added an item to the cart.

**Comment by walkward** [comment]
I have made the cart permanently accessible on mobile (simplest solution). Please let me know if you would prefer this to be available only when an item has been added to the cart.
