### ISSUE TITLE
Adding Too Many Items to Cart

### ISSUE THREAD

**Issue by cpoey** [walkward/veridicon-issues#15]
When adding a quantity of items that is more than what is in stock, some sort of warning/indicator should come up that the desired quantity cannot be fulfilled (at least immediately).

I added a qty of 25 Cover Tape PUA0375-300 even though it says that there are only 15 in stock.

Once in checkout, I am informed that there are inventory issues. Is this a limitation of Shopify? If so, such is life. If not, then I think the better user experience would be to inform user of the issue immediately.

**Comment by walkward** [comment]
I'm removing the toggle quantity feature from the cart. The cart is unaware of inventory levels. The product pages should limit the number of items added to the cart.
