### ISSUE TITLE
Surftape Products Are Not Separate From Carrier Tape

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#19]
@cpoey Creating an issue for reference.

I'm going to hide this product category until the database has been updated to distinguish carrier tape from surftape.

**Comment by walkward** [comment]
@cpoey Michael would like surftape to be combined with Carrier Tape. I'm going to append the surftape copy to the carrier tape copy.

I'll close this when you've confirmed this is okay.

**Comment by cpoey** [comment]
If that is what Michael wants, then let's do it!
