### ISSUE TITLE
Carrier Tape List Goes Back To Default

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#2]
CARRIER TAPE PG: When showing all Carrier Tape items, the list goes back to the default 10 items after adding an item to ‘Add to List’

**Comment by walkward** [comment]
@cpoey I don't completely understand this issue. Would you please provide an annotated screen shot? Or just a screen shot with description.

**Comment by cpoey** [comment]
Nevermind on this issue.  I did not write it properly.

One question - is there a way to go directly back to the Product page that you were on from the My List page, after you add an item to My List, then view it?

**Comment by walkward** [comment]
@cpoey Yes, we could add a "continue shopping" button. 

I might misunderstand your question though - is this something that couldn't be accomplished by using the browser's built-in button?
