### ISSUE TITLE
Mobile: Manual entry of quantity for a product

### ISSUE THREAD

**Issue by cpoey** [walkward/veridicon-issues#20]
Page layout is fine when 1st landing on a product category page. Upon tapping in quantity field to enter a number, keyboard presents itself from bottom of screen and the page zooms in about 20-25%.  When finished entering quantity and hiding the keyboard, the page does not zoom out to original position.

See 3 attached screen grabs

![mobile_after_qty_adjustment_no keyboard](https://user-images.githubusercontent.com/20300819/42063657-4b934844-7af8-11e8-9fdf-cb1d569c9579.jpeg)

![mobile_b4_qty_adjustment](https://user-images.githubusercontent.com/20300819/42063594-1335490c-7af8-11e8-96d1-fc1c1f2dc26d.jpeg)
![mobile_after_qty_adjustment](https://user-images.githubusercontent.com/20300819/42063595-134b7268-7af8-11e8-9d08-eaf2c47ba075.jpeg)

**Comment by walkward** [comment]
The fix for this is increasing the input font size from 14px to 16px - that would explain why some form elements might look slightly different.

I've also added some max/min checking for when product quantities are manually typed.
