### ISSUE TITLE
K0 Carrier Tape Range

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#27]
Can you remind me what the range is for the search.  I think the Min K0 considered might be too large (not considering enough parts)

**Comment by walkward** [comment]
Below are the details which were used for the search algorithm.

------------------------------

When inputting dimensions for a PART to find an appropriate pocket, the search should include all 
tapes that meet these requirements (all dimensions are in mm):

A0: input dimension + 0.2 to 1.0
AND
B0: input dimension + 0.2 to 1.0
AND
K0: input dimension + 0.2 to 1.0
 
The search results should be initially returned in order of closest B0 to farthest
 
I think we can eliminate the tolerance input by just asking that the input part dimensions be the MAX dimensions.  That’s all we care about for the initial search.
 
Also, I like the idea of having a button to choose whether you are entering PART dimensions or POCKET dimensions, with the default always being PART dimensions.

**Comment by VeridiMike** [comment]
I think the ranges we started with are reasonable:
If A0 input is 3.0, then all tapes with 3.2-4.0, inclusive, should be considered
If B0 input is 3.4, then all tapes with 3.6-4.4, inclusive, should be considered
If K0 input is 1.6, then all tapes with 1.8-2.6, inclusive, should be considered

Attached is what is returned when using the Advantek search
![tape search](https://user-images.githubusercontent.com/40769404/42227708-b7809c52-7ea7-11e8-8e02-e8958cc78f91.jpeg)
