### ISSUE TITLE
HID Text

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#4]
HUMIDITY INDICATOR CARDS: Not sure if this is a typo or not.  Top bullet point currently reads: 	Meets JEDEC J-STD-033 > Meets MIL-I-8835 and MIL-P-116 MTH II
Should the 2nd ‘Meets MIL…’ be a separate bullet point?

**Comment by walkward** [comment]
Copy deck uses current formatting - let me know if this should change anyway.

**Comment by cpoey** [comment]
I will check w/Michael on this.

**Comment by cpoey** [comment]
Make, 'Meets MIL-I-8835 and MIL-P-116 MTH II' a separate bullet point
