### ISSUE TITLE
Customer Accounts Created In Shopify Should Map To Customers In Fishbowl

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#47]
**The problem:** Currently, Fishbowl will use the billing "company name" to map customers internally. Unfortunately, there is no way to map orders to customer accounts using their account number. Duplicate accounts will be created if a user provides an alternate spelling of a company name. 

The following are options which would help prevent duplicate accounts from being created in Fishbowl:

1. Request that users provide the "legal business name" when creating new accounts.
2. Prevent users from creating "user-specific" accounts. During the account registration, users will not be asked for their first & last name but will instead be asked for their business name. If a user creates a company name which is different than the name in Fishbowl, the Shopify company name could be modified manually or the Fishbowl record could be modified to use the Shopify company name.
3. A single customer account could be used to represent all Shopify orders. This default account would represent all orders but each order would provide address and customer specific information.

**Payment terms:** This also relates to the way orders are fulfilled which may use Net D accounts. While there is no way of specifying the customer's payment terms when an account is created in Shopify, defaults could exist which define all new customers should use prepaid terms. The customer account could then be modified when a customer negotiates Net D terms with Veridicon.

Do any of these options work for your processes @VeridiMike ?

**Comment by VeridiMike** [comment]
Walker,

I think this is going to cause me a lot of headaches.  Regarding the 3 options listed below, I think the only feasible route is #2.  I think we will have to manually modify new accounts to existing companies.

Regarding Payment Terms, I think it is okay to have the only option up front be CC or pay in advance…with a message that different Terms can be set through Veridicon.

I am still unclear how a customer can see their company prices versus the list prices.  Example: List price for PLCC44-AC40.0P2 is $39.83, but A & J Programming’s price is $25.00

Thanks…Michael

**Comment by walkward** [comment]
I've been thinking more about this issue and would like to suggest an alternative which would avoid users from the same company sharing an account...

When a user signs up they will be asked for the following:

- First name
- Last name
- Company name
- Company email address (generic email addresses such as @gmail.com will not be allowed).
- Create a password

Then, when an account is created we will run a query to check if there are any other users with the same email address domain (if the company name is "Veridicon Technologies", all users with email addresses which are "@veridicon.com" will match). If an existing user has the same email address domain, the new user will be created with the exact same company name as the existing user. If there are no other users with the same email domain the user's account will be created with the company name they have listed during account registration.

This will mitigate issues relating to having multiple accounts for the same business while still allowing multiple accounts to be created by employees from the same company. Hopefully, this idea would make the registration process a bit smoother. But there are some other options we could explore if you see some issues here.

**Comment by VeridiMike** [comment]
I think this is a much more palatable solution.  The only thing I think about is the companies with multiple locations.  In one case, Micross, I have 1 Company with multiple Ship To addresses.  In another case, Benchmark, I have each location as a separate Company.  The reason being, Micross shares the same pricing across all locations, while Benchmark has pricing per location.  However, each Benchmark employee, no matter which location, has the same email domain: xxxx.xxxx@bench.com.
I think this is something I will have to manage internally if we go with this option.
