### ISSUE TITLE
Pitch missing

### ISSUE THREAD

**Issue by VeridiMike** [walkward/veridicon-issues#48]
I see in the carrier tape listings, A, B, K, K1, Length, width, pockets/reel show up correctly...but Pitch is left blank
![pitch](https://user-images.githubusercontent.com/40769404/43085929-cc2c600e-8e61-11e8-8414-0f2c950938a2.jpeg)

**Comment by walkward** [comment]
Thank you @VeridiMike, this has been fixed.
