### ISSUE TITLE
Image is to the right of the main Bands copy

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#6]
BANDS: Image is to the right of the main Bands copy, in the light grey section.  Every other product page has image below the copy, in the white section (I realize that there is no additional copy in white section).

**Comment by walkward** [comment]
This will change automatically if copy is added, otherwise it was quite unbalanced.

**Comment by walkward** [comment]
@cpoey Am I okay to close this? Any other changes need to be made?

**Comment by cpoey** [comment]
![img_703074006e27-1](https://user-images.githubusercontent.com/20300819/42047779-e122e676-7ac6-11e8-9283-4d0c1301f4ef.jpeg)

It looks like the image & gfx border need to be resized a bit to be a parallelogram, like the other images

**Comment by walkward** [comment]
@cpoey Okay, I've busted out the illustrator and have done the quickest thing without recreating the vectors...

![homepage-history](https://user-images.githubusercontent.com/19615034/42049839-7ea46a08-7ac4-11e8-9b50-6d83afdbd097.png)
