### ISSUE TITLE
Site Header Search

### ISSUE THREAD

**Issue by walkward** [walkward/veridicon-issues#8]
SITE SEARCH: search terms seem very rigid. Searching for ‘surftape’ gave me no results. Is there a way to employ predictive type?

**Comment by walkward** [comment]
There is not "Surftape" type in the DB, need to talk with Michael. The search uses predictive type but it doesn't always work well for product number (which are used for all product names). Try typing "D" and you should see the fuzzy search results.

**Comment by cpoey** [comment]
I think that we need to add search terms that relate to all of the top-level products that Veridicon sells, e.g. - Surftape, Desiccant, etc...  I will compile a list for you.

What are the technical ramifications of adding these terms to the db?

**Comment by cpoey** [comment]
[Veridicon Search Terms.zip](https://github.com/walkward/veridicon-issues/files/2147393/Veridicon.Search.Terms.zip)
Site Search Terms
