### ISSUE TITLE
HP Photo Replacement

### ISSUE THREAD

**Issue by cpoey** [walkward/veridicon-issues#9]
![veridicon_techphoto_03](https://user-images.githubusercontent.com/20300819/42037043-ec0930fa-7aac-11e8-99f3-27aeea8cea4e.jpg)

Replace Home Page photo, in History section (2nd photo of man holding circuit board) w/the attached photo.

In mobile space only, is it possible to have the image come 2nd in the vertical space? Currently, the flow is: CyberTech copy, CyberTech photo, History photo, History Copy.  Having the 2 images next to each other, vertically is awkward. I realize that we are doing the standard 2-column layout, but is there a way to override that in this scenario?

**Comment by walkward** [comment]
I have added the image and fixed the layout for mobile.
